# Generated by Django 4.2.4 on 2023-08-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verify_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_password',
            field=models.BooleanField(default=True, max_length=10),
        ),
    ]
